services:
  postgres:
    image: postgres:17
    container_name: PostgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: testDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/script.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U op"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "sleep 5 &&
             cd /app && 
             python run.py"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres_password@postgres:5432/testDB

volumes:
  postgres_data: