services:
  postgres:
    image: postgres:17
    container_name: PostgresDB
    environment:
      POSTGRES_USER: op
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: testDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U op"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4.2
    container_name: redis
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    command: >
      sh -c "sleep 5 &&
             cd /app &&
             alembic upgrade head &&
             uvicorn run:app --host 0.0.0.0 --port 80"
    environment:
      DATABASE_URL: postgresql+asyncpg://op:123456@localhost:8089/testDB
      REDIS_URL: redis://redis:6379

volumes:
  postgres_data:
  redis_data: